### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by jcayzac** [vektory79/plantuml-native-image#6]
Does the `Dockerfile` work for you? I tried it but am getting an error:

```
[plantuml:105]    classlist:  14,104.64 ms
[plantuml:105]        setup:     208.60 ms
Error: ImageSingletons.add must not overwrite existing key com.oracle.svm.core.CErrorNumber$CErrorNumberSupport
Existing value: com.oracle.svm.core.windows.WindowsCErrorNumberSupport@596ed9b9
New value: com.oracle.svm.core.posix.linux.LinuxCErrorNumberSupport@35f58cb7
com.oracle.svm.core.util.UserError$UserException: ImageSingletons.add must not overwrite existing key com.oracle.svm.core.CErrorNumber$CErrorNumberSupport
Existing value: com.oracle.svm.core.windows.WindowsCErrorNumberSupport@596ed9b9
New value: com.oracle.svm.core.posix.linux.LinuxCErrorNumberSupport@35f58cb7
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doAdd(ImageSingletonsSupportImpl.java:111)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl.add(ImageSingletonsSupportImpl.java:39)
	at org.graalvm.nativeimage.ImageSingletons.add(ImageSingletons.java:73)
	at com.oracle.svm.core.posix.linux.LinuxImageSingletonsFeature.afterRegistration(LinuxImageSingletonsFeature.java:38)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:812)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:812)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:24 min
[INFO] Finished at: 2020-05-01T07:05:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.nativeimage:native-image-maven-plugin:20.0.0:native-image (default) on project plantuml-graal: Execution of /opt/graalvm-ce-java8-19.3.1/jre/bin/native-image -cp /root/.m2/repository/org/graalvm/nativeimage/svm/20.0.0/svm-20.0.0.jar:/root/.m2/repository/org/graalvm/sdk/graal-sdk/20.0.0/graal-sdk-20.0.0.jar:/root/.m2/repository/org/graalvm/nativeimage/pointsto/20.0.0/pointsto-20.0.0.jar:/build/target/plantuml-graal-1.2020.2.jar --no-server --no-fallback -H:+ReportExceptionStackTraces --language:js -H:+TraceClassInitialization -cp /build/target/plantuml.jar -J-Xms5g -J-Xmx5g -H:Class=me.vektory79.plantuml.Main -H:Name=plantuml returned non-zero result -> [Help 1]
```

**Comment by jcayzac** [comment]
I've [also been trying to build plantuml as an executable](https://gist.github.com/jcayzac/0c1e2cb69cd6c89f4779557dbe18bab0) but hitting AWT errors at runtime (even in headless mode)

**Comment by vektory79** [comment]
Yes, indeed. I forgot update the GraalVM version in Dockerfile. Fixed in this commit: https://github.com/vektory79/plantuml-native-image/commit/021c76488ab0e31e46a383fe3ecdbbc259afab80

@jcayzac Thank that you a point me this!!!
